# Generated by Django 2.1.7 on 2019-05-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.Program', verbose_name='Curso'),
        ),
    ]
