# Generated by Django 2.1.7 on 2019-04-02 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JF_Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('statement', models.CharField(max_length=250)),
                ('topic_group', models.CharField(max_length=250)),
                ('correct_answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JudgmentFacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('team_length', models.IntegerField()),
                ('fact_max_time', models.TimeField()),
                ('status', model_utils.fields.StatusField(choices=[(1, 'Em criação'), (2, 'Em preparação'), (3, 'Em execução'), (4, 'Finalizado')], default=1, max_length=100, no_check_for_status=True)),
                ('fact', models.ManyToManyField(to='JF_Judgment_Facts.Fact')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_leader_set', to='JF_Login.Student')),
                ('member', models.ManyToManyField(related_name='student_member_set', to='JF_Login.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TeamFact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_answer', models.BooleanField()),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JF_Judgment_Facts.Fact')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JF_Judgment_Facts.Team')),
            ],
        ),
        migrations.AddField(
            model_name='judgmentfacts',
            name='team',
            field=models.ManyToManyField(to='JF_Judgment_Facts.Team'),
        ),
    ]
