# Generated by Django 2.1.7 on 2019-04-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JF_Judgment_Facts', '0001_initial'),
        ('JF_Login', '0001_initial'),
        ('JF_Academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JF_Login.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='judgment_facts',
            field=models.ManyToManyField(to='JF_Judgment_Facts.JudgmentFacts'),
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='JF_Login.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ManyToManyField(to='JF_Academic.Group'),
        ),
    ]
