# Generated by Django 2.1.7 on 2019-04-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('judgment_facts', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='judgment_facts',
            field=models.ManyToManyField(to='judgment_facts.JudgmentFacts'),
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='account.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ManyToManyField(to='academic.Group'),
        ),
    ]
