# Generated by Django 2.1.7 on 2019-04-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20190419_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='GroupStudent',
        ),
    ]
