# Generated by Django 2.1.7 on 2019-05-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_auto_20190428_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academic.Program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academic.Unit'),
            preserve_default=False,
        ),
    ]
