# Generated by Django 2.1.7 on 2019-05-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20190501_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='judgment_facts',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Course', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='group',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Program', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='account.Student', verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='group',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Unit', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='program',
            name='course',
            field=models.ManyToManyField(to='academic.Course', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='program',
            field=models.ManyToManyField(to='academic.Program', verbose_name='Curso'),
        ),
    ]
