# Generated by Django 2.1.7 on 2019-04-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgment_facts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgmentfacts',
            name='fact',
        ),
        migrations.AddField(
            model_name='fact',
            name='judgment_facts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='judgment_facts.JudgmentFacts'),
            preserve_default=False,
        ),
    ]
